### PR TITLE
replace request._fixturedefs by request._fixture_defs, solve issue #29

### PR DESCRIPTION
**Pull request by p13773**
SubRequest objects do not have any attribute '_fixturedefs' but an attribute '_fixture_defs' (see https://github.com/pytest-dev/pytest/blob/master/_pytest/fixtures.py#L588).
Pull request for this issue: https://github.com/pytest-dev/pytest-factoryboy/issues/29
(Solve a regression introduced in this commit : d5a37f5)

### CODE REVIEW

**Comment by a7p** [comment]
solves the issue for me

**Comment by prmtl** [comment]
Could you please also support pytest<3.0?

**Comment by thedrow** [comment]
This fixes the issue for me too.

**Comment by p13773** [comment]
Add support for pytest<3.0. Also remove support for python 2.6 due to too many dependencies problem and because python 2.6 is no longer supported by the Python core team.

**Comment by prmtl** [comment]
I would really appreciate that instead of copying my changes from #33 you could use 'cherry-pick' to keep my contribution.

**Comment by p13773** [comment]
Sorry I didn't see your previous commit. I modify my PR to include your code.

**Comment by thedrow** [comment]
Can we merge and release please? I'm currently using this PR in order to keep using pytest-factoryboy.

**Comment by bubenkoff** [comment]
thanks! 1.3.0 is out

**Comment by yobuntu** [comment]
1.3.1 still make the deprecated call to request.getfuncargsvalue()

**Comment by bubenkoff** [comment]
@yobuntu can you please make a PR to fix it?

**Comment by yobuntu** [comment]
i would but i just dit the same as https://github.com/pytest-dev/pytest-factoryboy/pull/30/files
which was closed instead of merged.

**Pull request merged**
