### PR TITLE
configure reorder-python-imports

### PR DESCRIPTION
**Pull request by graingert**
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-factoryboy/110)

### CODE REVIEW

**Comment by youtux** [comment]
Please explain why do we want to adopt such a code style.
Otherwise, this just looks unpythonic to me and I won't approve this change.

**Comment by graingert** [comment]
@asottile has some docs on why this style is important: https://github.com/asottile/reorder_python_imports#why-this-style

**Comment by youtux** [comment]
I see that it can indeed reduce merge conflicts for big projects that see a lot of changes.
But this project receives few contributions/changes per month, and the existing benefits of adopting this style can't quite keep up with odd code style.
It can actually be counter productive, resulting in a more convoluted development process just to make the commit hook pass.

**Comment by skarzi** [comment]
For me, this import's style is too verbose. For instance, [isort's `vertical Hanging Indent`](https://pycqa.github.io/isort/#multi-line-output-modes) applied for 2 or more imports is also really "mergeable", less verbose and in my opinion more pythonic.

**Comment by youtux** [comment]
If there are no other reason to adopt these changes, I will close this PR.

**Pull request closed without merging**
